name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Metabase Repo
        uses: actions/checkout@v3
        with:
          repository: metabase/metabase
          ref: v0.47.0

      - name: Checkout Driver Repo
        uses: actions/checkout@v3
        with:
          path: modules/drivers/materialize

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Install Clojure CLI
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.11.1.1262.sh &&
          sudo bash ./linux-install-1.11.1.1262.sh

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"

      - name: Get M2 cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-materialize-${{ hashFiles('**/deps.edn') }}

      - name: Prepare stuff for pulses
        run: yarn build-static-viz

      - name: Build Materialize driver
        run: |
          echo "{:deps {metabase/materialize {:local/root \"materialize\" }}}" > modules/drivers/deps.edn
          bin/build-driver.sh materialize
          ls -lah resources/modules

      - name: Install GitHub CLI
        run: |
          sudo apt update -y
          sudo apt install gh -y

      - name: Setup GitHub CLI
        working-directory: modules/drivers/materialize
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Release
        working-directory: modules/drivers/materialize
        run: |
          gh release create ${{ github.ref }} ../../../resources/modules/materialize.metabase-driver.jar -t "Release ${{ github.ref }}" -n "Release of the Materialize driver for Metabase"
